deploy:
    on:
        repo: CellProfiler/centrosome
        tags: true
    password:
        secure: qiTqut7Rft9LoRb7n0Ev7puZWSMfhWDxajeZ3DRwjt9cw50ViBWyIk6xCnjY7Yyrq8b5XJ/llnqjLAQ1Nh3zzAKS3IFbSTExQXucIgvwaEtfO7209ruU1Ar24q6gz+1qMBiTx8s5vcLvQNYAxqVozFnQcxy5Gme2YwjXclJamFj4Tzz/e37O1Tk6CXqyI1gdDUCl2b7Qxtb5vfjYiCE6u+9TArhOXtorDPQ9t0GOxVytgFocCN195IAL34CckQKLGutEYjO0ZoWNfgZ611HKw5K3MvTROAkBAQ6UdqA8twWTIknaxm9wFG1m04XrrSpHscQhAYNvM894g+4D28QXNobMmrd7trDjpTs9TguMkomCuNLict5hMsiutn72ZauB0iKbmc4CD2IEUHv4swcEH/7XQD2oGmTzskidpWk09pmxVFBRyP61ek+y4dAmYLpDqs/1nepUK3pedG96lvM0Ku23apcs1Lc57O1S2TfzvANUjfkZipOpuYZaYbKHEsCcDYFBvOZ6170AsR7TQfVuxpfFXdm8ORm3AtaRH1zSCxM6iXcin1sjJld/58aLZd0OUQj+/Gz5ZH5LAol7h/C1WN6A7KylBJV6dVc87jLUlOFl3QOC6ZruuocjTfQ+vDsW/80lBu63/LoJ9btwmoUyZdFSAvIB/vcHUH5BIvqRC0o=
    provider: pypi
    skip_cleanup: true
    user: "0x00B1"
install:
    - pip install --upgrade pip
    - pip install --upgrade wheel
    - pip install --upgrade cython
    - pip install --upgrade numpy
    - pip install --editable .
language: python
notifications:
    email: false
matrix:
    include:
        - python: 2.7
        - python: 3.5
        - python: 3.6
        - python: 3.7
          dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
          sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)
    allow_failures:
        - python: 3.5
        - python: 3.6
        - python: 3.7
before_script:
    - pip install flake8
    # stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
    - python setup.py test
sudo: false
