[workspace]
authors = ["Nodar Gogoberidze <gnodar01@gmail.com>"]
channels = ["conda-forge"]
description = "Dev environment for centrosome"
name = "centrosome"
platforms = ["osx-64"]

[tasks]
build = "python -m build"
tag = "$PIXI_PROJECT_ROOT/scripts/tag.sh"
publish = "twine upload dist/*"

[pypi-dependencies]
centrosome = { path = ".", extras = ["dev", "test"], editable = true }
setuptools = ">=75.6.0, <76"
build = ">=1.2.2.post1, <2"
twine = ">=6.0.1, <7"

[dependencies]
python = "3.9.*"
cython = "<3.0"
numpy = "*"
